name: Fight League Scheduler

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to click "Run Now" manually for testing

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up the odds sync
        run: curl -X GET https://testsitepicks.vercel.app//api/sync-odds
      
      - name: Wake up the results sync
        run: curl -X GET https://testsitepicks.vercel.app//api/sync-results